apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gke-auto-snapshot
spec:
  schedule: "* */6 * * *"
  startingDeadlineSeconds: 10800
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gke-auto-snapshot
            image: prodatakey/gke-auto-snapshot:latest
          restartPolicy: OnFailure
